### ISSUE TITLE
`dyn scan` isn't returning a valid JSON when multiple items found

### ISSUE THREAD

**Issue by phstc** [rlister/awful#2]
``` shell
dyn scan users > users.json
```

is returning:

``` json
{
 "id": "user1"
}
{ 
 "id": "user2"
}
```

instead of:

``` json
[{
 "id": "user1"
},
{ 
 "id": "user2"
}]
```

My suggestion is to make a uniform interface, always returning an array, even when there's a single item in the result set.

**Comment by rlister** [comment]
@phstc This is by design. Imagine some table with many GBs of data: you'd never want to slurp in its entire contents and parse the JSON in a single process. Any serious data-processing is probably going to do something more like map-reduce. Hence, the `dyn` tools are designed to operate line-by-line. Each line is self-contained valid JSON.

This is pretty standard practice for dynamodb scanning tools. See for example, https://github.com/markitx/dynamo-backup-to-s3, which uses the same data format.

If you do want a single JSON file, it should be pretty straightforward to insert surrounding braces and a bunch of commas, which is left as an exercise for the reader :-)

**Comment by phstc** [comment]
@rlister I see, maybe it could have an option `--pretty` to make it a valid JSON and pretty formatted (see #3) wdyt?

**Comment by phstc** [comment]
My motivation here and here #3 was to export data from a small table in DynamoDB and search using my text editor, so I could perform any kind of search that I wanted without worrying with PK, LSI and GSI constraints.

**Comment by rlister** [comment]
@phstc Well, one of the benefits of being a line-based tool is that it is very `grep` friendly. I'm not sure I see how your text editor needs the extra `[]` and `,` to be able to search. Can you explain more?

**Comment by phstc** [comment]
@rlister the visualization with `pretty` is better for human-eyes, I can easily see the entire item data and send to other people, instead of a single line JSON. I'm not using `dyn` for data automation, I'm using it to avoid going to AWS console and checking data manually. 

wdyt about an option `--pretty` to return a valid and pretty formatted JSON?
